<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Panel
    |--------------------------------------------------------------------------
    */

    'new_users' => 'New users',
    'user' => 'User',
    'users' => 'Users',
    'followers' => 'Followers',
    'following' => 'Following',
    'follow' => 'Follow',
    'unfollow' => 'Unfollow',
    'webinars' => 'Kursus',
    'webinar' => 'Kursus',
    'webinar_sales' => 'Live class sales',
    'content_sales' => 'Sales',
    'my_webinars' => 'Kursus',
    'you_not_have_any_webinar' => 'Tidak ada Kursus!',
    'no_result_hint' => 'Buat kursus pertama Anda dan biarkan orang lain belajar dari Anda.',
    'choose_webinar' => 'Pilihan Kursus',
    'certificates' => 'Sertifikat',
    'quizzes' => 'Kuiz',
    'financial' => 'Keuangan',
    'requests' => 'Permintaan',
    'support' => 'Dukungan',
    'send_new_support' => 'Pesan dukungan baru',
    'notifications' => 'Notifikasi',
    'settings' => 'Pengaturan',
    'log_out' => 'Log out',
    'create_a_class' => 'Buat kursus',
    'create_a_webinar' => 'Buat kursus',

    'invited_classes' => 'Kursus yang diundang',
    'invited_teacher' => 'Instruktur yang di undang',
    'invited_by' => 'Diundang oleh',
    'classes' => 'Kursus',
    'my_classes' => 'Kursus',
    'my_activity' => 'Aktifitas',
    'download_sales' => 'Download Penjualan',
    'course_sales' => 'Penjualan',
    'only_not_conducted_webinars' => 'Hanya saja tidak dilakukan pada kelas langsung',
    'conducted' => 'Diadakan',
    'not_conducted' => 'Ditiadakan',

    'upcoming' => 'Mendatang',
    'start_learning' => 'Mulailah belajar',
    'my_purchases_no_result' => 'Tidak ada kursus yang dibeli!',
    'my_purchases_no_result_hint' => 'Mulailah belajar dari instruktur terbaik dan nikmatilah...',

    'comment' => 'Komen',
    'comments' => 'Komen',
    'reply' => 'Membalas',
    'replied' => 'Balasan',
    'not_replied' => 'Tidak balasan',
    'report' => 'Report',
    'report_success' => 'Laporan anda sudah dikirim.',
    'report_fail' => 'Laporan gagal, pastikan anda sudah logged in.',
    'new_comments' => 'Komentar baru',
    'my_class_comments' => 'Komentar kursusku',
    'my_comments' => 'Komentarku',
    'comments_statistics' => 'Statistik komentar',
    'filter_comments' => 'Filter komentar',
    'webinar_comments_list' => 'Daftar komentar kursus',
    'comments_no_result' => 'Anda tidak memiliki komentar apa pun!',
    'comments_no_result_hint' => "Ketika seorang siswa mengomentari kursus Anda \n komentar tersebut akan muncul di daftar ini.",
    'my_comments_no_result' => 'Anda tidak membuat komentar apa pun!',
    'my_comments_no_result_hint' => "Komentar Anda akan membantu meningkatkan kualitas komunitas...",

    'my_purchases' => 'Pembelian',
    'no_result_purchases' => 'Tidak Ada Kursus yang Dibeli!',
    'no_result_purchases_hint' => 'Start learning from the best instructors and enjoy...',
    'purchase_date' => 'Purchase Date',
    'purchased' => 'Purchased',

    'favorites' => 'Favorit',
    'favorite' => 'Favorit',
    'favorite_live_classes' => 'Kursus favorit',
    'no_result_favorites' => 'Tidak kursus favorit!',
    'no_result_favorites_hint' => 'Anda dapat menambahkan kursus ke favorit Anda dan mendaftar di lain waktu.',

    'meeting' => 'Meeting',
    'meetings' => 'Meetings',
    'open_meetings' => 'Meeting terbuka',
    'pending_appointments' => 'Meeting yang tertunda',
    'total_meetings' => 'Jumlah meeting',
    'amount' => 'Jumlah',
    'sales' => 'Penjualan',
    'sales_amount' => 'Jumlah penjualan',
    'active_hours' => 'Jam Aktif',
    'meeting_statistics' => 'Statistik meeting',
    'filter_meetings' => 'Filter meeting',
    'meeting_list' => 'Daftar meeting',
    'meeting_requests_list' => 'Daftar permintaan meeting',
    'show_only_open_meetings' => 'Show only open meetings',
    'create_link' => 'Buat link',
    'contact_student' => 'Kontak siswa',
    'contact_instructor' => 'Kontak instruktur',
    'finish_meeting' => 'Finish meeting',
    'meeting_no_result' => 'Tidak ada permintaan meeting!',
    'meeting_no_result_hint' => 'Reservasi meetings akan ditampilkan didalam list ini.',
    'student_contact_information' => 'Informasi kontak siswa',
    'instructor_contact_information' => 'Informasi kontak instruktur',
    'my_timesheet' => 'Lembar waktu saya',
    'saturday' => 'Sabtu',
    'sunday' => 'Minggu',
    'monday' => 'Senen',
    'tuesday' => 'Selasa',
    'wednesday' => 'Rabu',
    'thursday' => 'Kamis',
    'friday' => 'Jumat',
    'join_live_meeting' => 'Bergabung live meeting',
    'add_live_meeting_link' => 'Tambahkan live meeting link',
    'add_live_meeting_link_success' => 'Live meeting link berhasil ditambahkan',
    'add_live_meeting_link_fail' => 'Error saat menambahkan live meeting link',
    'add_live_meeting_link_hint' => 'Andan bisa menggunakan Zoom, Bigbluebutton, etc links',
    'url' => 'URL',
    'my_hourly_charge' => 'Biaya per jam',
    'number_only' => 'Hanya nomor...',
    'temporary_disable_meetings' => 'Nonaktif sementara meetings',
    'success_temporary_disable_meetings' => 'Meetings berhasil dinonaktifkan.',
    'error_temporary_disable_meetings' => 'Gagal menonaktifkan meetings.',
    'discount' => 'Potongan harga',

    // dashboard
    'dashboard' => 'Dashboard',
    'i_not_available' => 'Aktifkan offline status',
    'hi' => 'Hi',
    'have_event' => 'Andan memiliki :count event barus',
    'view_all_events' => 'Lihat semua events',
    'account_balance' => 'Saldo Rekening',
    'with_drawable' => 'Dapat ditarik',
    'live_requests' => 'Permintaan Meeting',
    'monthly_sales' => 'Penjualan bulanan',
    'learning_statistics' => 'Statistik pembelajaran',
    'support_messages' => 'Pesan Dukungan',
    'next_badge' => 'Next Badge',
    'noticeboard' => 'Papan Pengumuman',
    'noticeboards' => 'Pengumuman',
    'not_verified_alert' => 'Identitas dan informasi keuangan Anda tidak terverifikasi sehingga dapat menyebabkan keterlambatan dalam proses pembayaran. Silakan definisikan ',
    'this_link' => 'pengaturan',
    // Conversations
    'conversations' => 'Percakapan',
    'create_support_message' => 'Pesan dukungan baru',
    'course_support' => 'Dukungan kursus',
    'course_type' => 'Jenis kursus',
    'platform_support' => 'Platform yang didukung',
    'department' => 'Departemen',
    'attach' => 'Attachment',
    'attach_file' => 'Attach a file',
    'open_conversations' => 'Percakapan terbukan',
    'closed_conversations' => 'Percakapan tertutup',
    'total_conversations' => 'Jumlah percakapan',
    'messages_history' => 'Riwayat pesan',
    'support_summary' => 'Ringkasan dukungan',
  	'classes_support' => 'Dukungan kursus',
  	'support_tickets' => 'Tiket',
    'staff' => 'Staf',
    'teacher' => 'Instrutur',
    'open' => 'Open',
    'closed' => 'Closed',
    'close_request' => 'Close request',
    'reply_to_the_conversation' => 'Balas percakapan',
    'support_no_result' => 'Anda tidak memiliki pesan dukungan',
    'support_no_result_hint' => 'Anda bisa menghubungi instruktuktur dan platform support team.',

    'select_support' => 'Pilihan percakapan',
    'select_support_hint' => 'Silakan pilih percakapan dukungan untuk menampilkan riwayat pesan.',
    'message_filters' => 'Filter pesan',

    // notifications
    'notification_no_result' => 'Tidaka ada notifikasi.',
    'notification_no_result_hint' => 'Setiap even penting akan diberitahukan ke anda...',

    // comments
    'show_only_new_comments' => 'Tampilkan komentar terbaru',
    'reply_to_the_comment' => 'Balas komentar',
    'edit_comment' => 'Edit comment',

    //Marketing
    'marketing' => 'Marketing',
    'discounts' => 'Potongan',
    'create_a_new_discount' => 'Diskon kursus baru',
    'create_a_new_special_offer' => 'Buat penawaran khusus baru',
    'show_only_active_discounts' => 'Tampilkan hanya diskon aktif',
    'discount_no_result' => 'Tidak ada diskon yang tersedia...',
    'discount_no_result_hint' => 'Anda dapat membuat diskon dan meningkatkan penjualan Anda.',
    'special_offers_no_result' => 'Tidak ada diskon...',
    'special_offers_no_result_hint' => 'Anda dapat menambahkan diskon ke kursus Anda dan meningkatkan penjualan Anda.',

    'promotion' => 'Promosi',
    'promotions' => 'Promosi',
    'select_promotion_plan' => 'Pilih rencana promosi',
    'promotions_history' => 'Riwayat promosi',
    'promotion_days' => 'Untuk :day hari',
    'select_course' => 'Pilihan kursus',
    'show_only_active_promotions' => 'Tampilkan hanya promosi yang aktif',
    'popular' => 'Popular',
    'plan' => 'Rencana',
    'pay' => 'Bayar',
    'expired' => 'Expired',
    'promote_the_webinar' => 'Promosi kursus',
    'select_webinar_for_promotion' => 'Silakan pilih kursus yang ingin Anda promosikan.',
    'promotion_no_result' => 'Tidak ada Promosi!',
    'promotion_no_result_hint' => 'Dengan mengaktifkan rencana promosi, Anda dapat meningkatkan tampilan kursus dan penjualan.',

    // Instructors
    'filter_instructors' => 'Filter Instruktur',
    'instructors_list' => 'Instrutur List',
    'add_an_instructor' => 'Instruktur baru',
    'instructors_no_result' => 'Belum ada instruktur yang ditambahkan!',
    'instructors_no_result_hint' => 'Anda dapat membuat instruktur yang terkait dengan organisasi.',

    'filter_students' => 'Filter Siswa',
    'students_list' => 'Daftar siswa',
    'add_an_student' => 'Siswa baru',
    'students_no_result' => 'Belum ada siswa yang ditambahkan!',
    'students_no_result_hint' => 'Anda dapat menambahkan siswa organisasi Anda dengan mudah.',

    'meeting_sales' => 'Meeting Penjualan',
    'appointment_sales' => 'Meeting Penjualan',

    'bio' => 'Biography',
    'job_title' => 'Judul Pekerjaan',
    'bio_hint_1' => '"Judul pekerjaan" akan ditampilkan di bagian bawah nama Anda pada kartu profil.',
    'bio_hint_2' => 'Singkat saja (2 atau 3 kata) Misalnya "Desainer produk, Insinyur perangkat lunak senior".',
    'interests_hint_1' => 'Memilih topik yang menarik (untuk instruktur) akan membantu siswa menemukan Anda untuk live meetings.',
    'interests_hint_2' => 'Jika Anda melakukan live meeting, pilih topik yang disarankan lebih akurat.',
    'not_assign_any_webinar' => 'Tidak ditugaskan pada kursus apa pun',
    'active' => 'Active',
    'inactive' => 'Disable',
    'name' => 'Name',
    'special_offers' => 'Penawaran khusus',
    'special_offer' => 'Penawaran khusus',
    'show_only_active_special_offers' => 'Hanya Tampilkan Penawaran Khusus Aktif',

    'offline_title' => 'Aktifkan offline status',
    'offline_message' => 'Offline message',
    'offline_success' => 'Status Anda berhasil diubah!',
    'offline_hint' => 'Jika anda offline, pesan akan ditampilkan di profile anda dan akan di beritahukan ke users. Anda dapat mengetikkan pesan yang dipersonalisasi di input berikut.',

    // months
    'month_1' => 'Jan',
    'month_2' => 'Feb',
    'month_3' => 'Mar',
    'month_4' => 'Apr',
    'month_5' => 'May',
    'month_6' => 'Jun',
    'month_7' => 'Jul',
    'month_8' => 'Aug',
    'month_9' => 'Sep',
    'month_10' => 'Oct',
    'month_11' => 'Nov',
    'month_12' => 'Dec',

    'user_setting_success' => 'Informasi anda berhasil diperbaharui',

    'remaining' => 'Remained',

    'organization_classes' => 'Kursus organisasi',
    'filter_classes' => 'Filter kursus',
    'only_not_free_classes' => 'Hanya kursus berbayar',
    'only_free_classes' => 'Hanya kursus gratis',

    'new_noticeboard' => 'Pemberitahuan baru',
    'noticeboard_success_send' => 'Pemberitahuan baru berhasi dikirim',
    'noticeboard_success_send_to' => ':users_count Pengumuman baru berhasil dikirim',

    'more_info' => 'Info lebih lanjut',
  	'partner_instructor_hint' => 'Mitra Instruktur akan memiliki akses ke konten kursus dan profil mereka akan ditampilkan di halaman kursus.',
  	
  	'affiliate' => 'Afiliasi',
    'affiliates' => 'Afiliasi',
    'affiliates_page' => 'Afiliasi Marketing',
    'affiliate_statistics' => 'Statistik Afiliasi',
    'affiliate_summary' => 'Ringkasan Afiliasi',
    'earnings' => 'Pendapatan',
    'referred_users' => 'Referred Users',
    'registration_bonus' => 'Bonus Registstrasi',
    'affiliate_bonus' => 'Komisi penjualan',
    'registration_date' => 'Tanggal Registrasi',
    'user_registration_reward' => 'Penghasilan Anda dari setiap pendaftaran pengguna yang dirujuk',
    'referred_user_purchase_commission' => 'Komisi Anda dari pembelian pengguna yang dirujuk',
    'referred_user_registration_reward' => 'Pendapatan pengguna yang dirujuk saat mendaftar dengan kode afiliasi Anda',
    'your_affiliate_code' => 'Kode afiliasi anda',
    'affiliate_url' => 'URL Afiliasi anda',
	'content_defined' => 'Isi Ditentukan',
  	'purchased_courses' => 'Kursus yang dibeli',
];
