<?php

return [

    /*
    |--------------------------------------------------------------------------
    | General Translations
    |--------------------------------------------------------------------------
    */

    'title' => 'Judul',
    'sub_title' => 'Sub-Judul',
    'name' => 'Nama',
    'seo_description' => 'SEO Meta Description',
    'cover_image' => 'Cover gambar',
    'thumbnail_image' => 'Thumbnail',
    'image' => 'Gambar',
  	'images' => 'Gambar',
    'demo_video' => 'Demo Video',
    'optional' => 'Optional',
    'description' => 'Deskripsi',
    'summary' => 'Ringkasan',
    'study_time' => 'Waktu Belajar',
    'date_time' => 'Tanggal/Waktu',
    'availability_times' => 'Ketersediaan Waktu',
    'available' => 'Tersedia',
    'available_for_meetings' => 'Tersedia untuk Meetings',
    'meeting' => 'Meeting',
    'meetings' => 'Meetings',
    'link' => 'Link',
    'duration' => 'Durasi',
    'minutes' => 'Menit',
    'min' => 'Min',
    'view' => 'View',
    'view_profile' => 'View Profile',
    'review_or_edit' => 'Review/Edit',
    'review' => 'Review',
    'invited' => 'Invited',
    'try_again' => 'Coba lagi',
    'you_can_try_again' => 'Jangan khawatir, anda bisa mencoba kembali.',
    'start' => 'Start',
    'volume' => 'Volume',
    'file_type' => 'File Type',
    'accessibility' => 'Accessibility',
    'choose_accessibility' => 'Gratis atau Berbayar?',
    'attachments' => 'Attachments',
    'choose_attachments' => 'Pilih file terkait sebagai lampiran pelajaran',
    'paid' => 'Bayar',
    'paid_amount' => 'Jumlah Pembayaran',
    'instructor' => 'Instruktur',
    'instructors' => 'Instruktur',
    'students' => 'Pelajar',
    'students_and_instructors' => 'Pelajar dan Instruktur',
    'search_instructors' => 'Cari Instrurktur...',
    'publish_date' => 'Tanggal diterbitkan',
    'forced' => 'Terpaksa',
    'yes' => 'Ya',
    'no' => 'Tidak',

    'course_sessions' => 'Sesi Kelas',
    'previous_lesson' => 'Pelajaran Sebelumnya',
    'next_lesson' => 'Pelajaran Sesudahnya',

    'drag_to_change_order' => 'Seret untuk mengubah urutan',

    'controls' => 'Actions',
    'phone' => 'Phone',
    'mobile' => 'Phone',
    'email' => 'Email',

    'add_time' => 'Tambahkan Waktu',
    'clear_all' => 'Bersihkan semua',
    'additional_information' => 'Informasi Tambahan',
    'capacity' => 'Kapasitas',
    'start_date' => 'Mulai Tanggal',
    'time' => 'Waktu',
    'date' => 'Tanggal',
    'date_created' => 'Tanggal dibuat',
    'partner_instructor' => 'Mitra Instruktur',
    'subscribe' => 'Langganan',
    'add_to_cart' => 'Tambahkan ke keranjang',
    'add_to_calendar' => 'Tambahkan ke kalender',
    'add_to' => 'Tambahkan',
    'reminder' => 'Pengingat',
    'calendar' => 'Kalender',
    'price' => 'Harga',
    '0_for_free' => 'Masukkan 0 untuk gratis',
    'free' => 'Gratis',
    'enroll_on_webinar' => 'Mendaftar di Kursus',
    'free_meetings' => 'Meeting Gratis',
    'select_a_partner_teacher' => 'Pilih mitra Instruktur',
    'select_a_teacher' => 'Pilih Instruktur',
    'choose_instructor' => 'Pilih Instruktur',
    'search' => 'Cari',
    'search_instructor' => 'Cari nama,email atau telpon instruktur',
    'search_user' => 'Cari user',
    'tags' => 'Tags',
    'type_tag_name_and_press_enter' => 'Ketik nama tag dan tekan enter',
    'moderator_password' => 'Moderator Password',

    'category' => 'Kategori',
    'choose_category' => 'Pilih Kategori',
    'category_filters' => 'Filter Kategori',
    'tickets' => 'Tiket',
    'add_ticket' => 'Paket Harga Baru',
    'add_plan' => 'Paket baru',
    'add_new_ticket' => 'Paket Harga Baru',
    'discount' => 'Diskon',
    'ticket_no_result' => 'Tidak ada paket harga!',
    'ticket_no_result_hint' => 'Dengan membuat perencanaan harga, Anda dapat menambahkan harga yang bergantung pada waktu dan kapasitas untuk kursus Anda.',

    'edit' => 'Edit',
    'delete' => 'Delete',
    'remove' => 'Remove',

    'list' => 'Daftar',
    'reservation' => 'Reservasi',
    'my_reservation' => 'Reservasi',
    'result' => 'Hasil',
    'results' => 'Hasil',
    'my_results' => 'Pencapaian',

    'all' => 'Semua',
    'sessions' => 'Sesi',
    'add_session' => 'Sesi Baru',
    'add_new_sessions' => 'New Live Session',
    'sessions_no_result' => 'No live sessions!',
    'sessions_no_result_hint' => 'Anda dapat membuat sesi langsung sehingga siswa dapat bergabung dan mulai belajar.',
    'create_join_link' => 'Buat tautan bergabung',

    'newest' => 'Terbaru',
    'expensive' => 'Harga Tertinggi',
    'inexpensive' => 'Harga Terendah',
    'bestsellers' => 'Penjualan terbaik',
    'best_rates' => 'Penilaian Terbaik',

    'files' => 'Files',
    'file' => 'File',
    'source' => 'Source',
    'add_files' => 'New File',
    'add_new_files' => 'Add new file',
    'files_no_result' => 'No file is defined!',
    'files_no_result_hint' => 'Anda dapat menentukan bagian video kursus, proyek, lampiran, dan latihan sebagai file.',

    'test_lesson' => 'Teks Pembelajaran',
    'lesson' => 'Pembelajaran',
    'add_test_lesson' => 'Teks pembelajaran baru',
    'add_new_test_lesson' => 'Tambahkan teks pembelajaran baru',
    'text_lesson_no_result' => 'Tidak ada pelajaran teks!',
    'text_lesson_no_result_hint' => 'Buat pelajaran teks sehingga siswa dapat mendaftar dan mulai belajar.',

    'prerequisites' => 'Prasyarat',
    'add_prerequisites' => 'Prasyarat baru',
    'add_new_prerequisites' => 'Tambahkan Prasyarat baru',
    'select_prerequisites' => 'Pilih Prasyarat',
    'search_prerequisites' => 'Cari prasyarat',
    'prerequisites_no_result' => 'Tidak ada prasyarat yang didefinisikan!',
    'prerequisites_no_result_hint' => 'Anda dapat membuat prasyarat yang diwajibkan atau disarankan agar siswa dapat belajar lebih baik.',

    'basic_information' => 'Basic Informasi',
    'extra_information' => 'Extra Informasi',
    'pricing' => 'Harga',
    'content' => 'Isi',

    'faq' => 'FAQ',
    'add_faq' => 'New FAQ',
    'answer' => 'Menjawab',
    'answers' => 'Menjawab',
    'view_answers' => 'Lihat Jawaban',
    'faq_no_result' => 'Tidak ada FAQ yang di definisikan!',
    'faq_no_result_hint' => 'Dengan membuat FAQ, Anda akan membantu pengguna mengetahui lebih banyak tentang kursus Anda.',

    'quiz_certificate' => 'Kuis & Sertifikasi',
    'certificate' => 'Sertifikat',
    'certificate_id' => 'Sertifikat ID',
    'certificate_and_documents' => 'Sertifikat & Dokumen',
    'add_quiz' => 'Kuis Baru',
    'add_new_quizzes' => 'Kuis Baru',
    'select_a_quiz' => 'Pilih Kuis',
    'quiz' => 'Kuis',
    'questions' => 'Pertanyaan',
    'total_mark' => 'Nilai Total',
    'pass_mark' => 'Nilai Lulus',
    'mark' => 'Nilai',
    'not_participated' => 'Tidak Berpartisipasi',
    'dont_have_quiz' => 'Anda tidak memiliki kuis, tolong tentunkan dulu kuis nya.',
    'quizzes_no_result' => 'Tidak ada Kuis yang dipilih untuk kursus ini.',
    'quizzes_no_result_hint' => 'Dengan membuat kuis, Anda dapat mengevaluasi siswa dan memberikan sertifikat kepada mereka.',

    'agree_rules' => 'Saya setuju dengan syarat & ketentuan.',

    'message_to_reviewer' => 'Message to reviewer',

    'send_for_review' => 'Send for Review',
    'save_as_draft' => 'Save as Draft',
    'draft' => 'Draft',
    'waiting' => 'Waiting',
    'done' => 'Done',
    'reject' => 'Reject',
    'rejected' => 'Rejected',

    'close' => 'Close',
    'save' => 'Save',
    'continue' => 'Continue',
    'submit' => 'Save',
    'new' => 'New',
    'history' => 'History',
    'item_id' => 'Item ID',
    'export_list' => 'Export students list',
    'duplicate' => 'Duplicate',

    'updated_at' => 'Updated Date',
    'from' => 'From',
    'to' => 'To',
    'show_results' => 'Show Results',
    'status' => 'Status',
    'published' => 'Published',
    'type' => 'Type',
    'active' => 'Active',
    'verified' => 'Verified',
    'not_verified' => 'Not Verified',
    'inactive' => 'Disable',
    'disabled' => 'Disabled',
    'disable' => 'Disable',
    'open' => 'Open',
    'invoice' => 'Invoice',
    'feedback' => 'Feedback',
    'by' => 'By',
    'finish' => 'Finish',
    'finished' => 'Finished',
    'pending' => 'Pending',
    'selected' => 'Selected',
    'select' => 'Select',
    'required' => 'Required',
    'not_bought' => 'Not Purchased!',
    'not_access' => 'Access Denied!',
    'not_access_to_this_content' => 'Anda tidak memiliki akses untuk kontent ini',
    'play' => 'Play',
    'play_online' => 'Play (Stream)',
    'read' => 'Read',

    'are_you_sure' => 'Anda yakin?',
    'deleteAlertHint' => "Tindakan ini tidak bisa dibatalkan!",
    'deleteAlertConfirm' => 'Delete',
    'deleteAlertFailHint' => 'Error while deleting item!',
    'deleteAlertSuccessHint' => 'Item successfully deleted.',
    'cancel' => 'Cancel',
    'canceled' => 'Canceled',
    'success' => 'Success',
    'fail' => 'Failed',

    'unavailable' => 'Unavailable',
    'unavailable_description' => 'Unavailability message',

    'not_defined' => 'Not defined',

    'days' => 'Days',
    'day' => 'Day',
    'hr' => 'Hr',
    'sec' => 'Sec',
    'off' => 'Off',
    'offer' => ':off% Offer',

    'sort_by' => 'Sort by',
    'in' => 'in',
    'created_by' => 'Created by',
    'created_at' => 'Created Date',
    'created' => 'Created',
    'create' => 'Create',
    'save_change' => 'Save',
    'ratings' => 'Ratings',

    'share' => 'Share',
    'share_this_course_with_others' => 'Bagikan kursus dengan teman Anda',
    'profile' => 'Profile',
    'telegram' => 'Telegram',
    'facebook' => 'Facebook',
    'whatsapp' => 'Whatsapp',
    'twitter' => 'Twitter',
    'book_a_meeting' => 'Book a Meeting',
    'author_posts' => 'Author Posts',
    'reserve_a_meeting' => 'Reserve a Meeting',
    'go_to_class' => 'Go to Course',
    'go_to_settings' => 'Go to Settings',
    'course_page_title' => 'Course',

    'duplicate_review_for_webinar' => 'Tinjauan duplikat untuk kursus',
    'creator' => 'Creator',
    'manual' => 'Manual',
    'automatic' => 'Automatic',
    'start_payment' => 'Start Pembayaran',
    'pay' => 'Bayar',
    'saturday' => 'Sabtu',
    'sunday' => 'Minggu',
    'monday' => 'Senin',
    'tuesday' => 'Selasa',
    'wednesday' => 'Rabu',
    'thursday' => 'Kamis',
    'friday' => 'Jumat',
    'all_days' => 'Semua hari',

    'my_panel' => 'My Panel',
    'my_profile' => 'My Profile',
    'user_profille_page_title' => 'User Profile',
    'edit_selected_image' => 'Crop selected image',

    'request_failed' => 'Request Failed',
    'request_success' => 'Request done successfully!',

    'cart_page_title' => 'Keranjang',
    'checkout_page_title' => 'Checkout',
    'channel_payment_disabled' => 'Gerbang pembayaran dinonaktifkan.',
    'income_los_then_minimum_payout' => 'Penghasilan Anda kurang dari jumlah pembayaran minimum.Harap tunggu untuk melewati batasan.',

    'paid_form_online_payment' => 'Pembayaran online',
    'paid_form_credit' => 'Formulir pembayaran kredit',
    'paid_for_sale' => 'Dibayar untuk dijual',
    'tax_get_form_buyer' => 'Form pajak pembeli',
    'income_sale' => 'Pendapatan penjualan',
    'paid_for_commission' => 'Dibayar untuk komisi',
    'get_commission_from_seller' => 'Komisi penjual',
    'get_commission_from_referral' => 'Pendapatan Afiliasi',
    'get_amount_from_referral' => 'Pendapatan Afiliasi',
    'refund_money_to_buyer' => 'Dikembalikan ke pembeli',
    'refund_tax' => 'Pajak yang dikembalikan',
    'refund_commission_to_seller' => 'Komisi yang dikembalikan kepada penjual',
    'refund_commission' => 'Komisi yang dikembalikan',
    'refund_income' => 'Pendapatan yang dikembalikan',
    'charge_account' => 'Tagihan akun',
    'withdraw_account' => 'Tarik saldo',
    'income_for_subscribe' => 'Pendapatan berlangganan item',
    'paid_form_subscribe' => 'Dibayar menggunakan langganan',
    'income_for_promotion' => 'Dibayar untuk promosi',

    'ticket_for_students_until_date' => 'Untuk :students pelajar pertama sampai tanggal :date',
    'ticket_until_date' => 'sampai tanggal :date',

    'about' => 'Tentang',
    'specifications' => 'Spesifikasi',
    'educations' => 'Edukasi',
    'experiences' => 'Pengalaman',
    'occupations' => 'Topik Keterampilan',
    'identity_and_financial' => 'Identitas & Keuangan',

    'copy' => 'Copy',
    'copied' => 'Copied',
    'user_role' => 'User Type',
    'all_roles' => 'All Types',

    'error_404_page_title' => 'Halaman tidak di temukan',
    'i_passed_this_lesson' => 'Saya lulus pelajaran ini',
    'course_learning_change_status_success' => 'Status belajar Anda berhasil diubah.',
    'course_learning_change_status_error' => 'Gagal mengubah status pembelajaran.',
    'course_learning_passed' => ':percent% kursus terlewati.',

    'not_login_toast_lang' => 'Konten Terbatas',
    'not_login_toast_msg_lang' => 'Silakan login untuk mengakses konten',
    'not_access_toast_lang' => 'Akses ditolak',
    'not_access_toast_msg_lang' => 'Anda tidak memiliki akses ke konten ini.',
    'can_not_try_again_quiz_toast_lang' => 'Mengulurkan tangan',
    'can_not_try_again_quiz_toast_msg_lang' => 'Anda tidak dapat mengikuti kuis ini lagi.',
    'can_not_download_certificate_toast_lang' => 'Download gagal',
    'can_not_download_certificate_toast_msg_lang' => 'Anda tidak dapat mengunduh sertifikat ini.',
    'session_finished_toast_title_lang' => 'Sesi Selesai',
    'session_finished_toast_msg_lang' => 'Anda terlambat, sesi ini selesai.',

    'zoom_api' => 'Zoom API',
    'zoom_jwt_token' => 'Zoom JWT Token',
 	  'how_zoom_jwt_token' => 'Cara membuat Zoom JWT token',
    'instructor_is_not_available' => 'Instruktur untuk sementara tidak tersedia.',
  
    'chapter' => 'Bagian',
    'chapters' => 'Bagian',
    'add_new_chapter' => 'Tambahkan Bagian Baru',
    'add_text_lesson' => 'Pelajaran Teks Baru',
    'new_chapter' => 'Bagian Baru',
    'edit_chapter' => 'Edit Bagian',
    'chapter_title' => 'Judul Bagian',
    'topic' => 'Tema',
    'parts' => 'Bagian',
  	'content_defined' => 'Konten Didefinisikan',
    'no_chapter' => 'Tidak Ada Bagian',
  	'add_file' => 'File Baru',
    'topic_post' => 'Postingan Topik',

    'forbidden_request_toast_lang' => '"FORBIDDEN" Request',
    'forbidden_request_toast_msg_lang' => 'Anda tidak mengakses konten ini.',

];
